version: '3'

services:
  node:
    image: node:latest
    command: tail -f /dev/null
    volumes:
      - "./:/var/www"
    ports:
      - "3000:3000"
    environment:
      - URL_MONGO=mongodb://root:root@mongo
    networks:
      zd_proxy_network:

  mongo:
    image: mongo:6.0.3
    volumes:
      - "./mongo/data:/data/db"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      zd_proxy_network:

  mongo-express:
    image: mongo-express
    ports:
      - "8888:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    depends_on:
      - mongo
    networks:
      zd_proxy_network:

networks:
  zd_proxy_network:
    driver: bridge